### ISSUE TITLE
Error trying to test the emulator on Windows

### ISSUE THREAD

**Issue by mlinaje** [ZubinGou/8086-emulator#1]
Traceback (most recent call last):
  File "C:\Users\usuario2\Downloads\8086-emulator-master\ui\codeeditor.py", line 150, in paintEvent
    self.codeEditor.lineNumberAreaPaintEvent(event)
  File "C:\Users\usuario2\Downloads\8086-emulator-master\ui\codeeditor.py", line 52, in lineNumberAreaPaintEvent
    painter.drawText(0, top, areaWidth - rightMargin,
TypeError: arguments did not match any overloaded call:
  drawText(self, p: Union[QPointF, QPoint], s: str): argument 1 has unexpected type 'int'
  drawText(self, rectangle: QRectF, flags: int, text: str): argument 1 has unexpected type 'int'
  drawText(self, rectangle: QRect, flags: int, text: str): argument 1 has unexpected type 'int'
  drawText(self, rectangle: QRectF, text: str, option: QTextOption = QTextOption()): argument 1 has unexpected type 'int'
  drawText(self, p: QPoint, s: str): argument 1 has unexpected type 'int'
  drawText(self, x: int, y: int, width: int, height: int, flags: int, text: str): argument 2 has unexpected type 'float'
  drawText(self, x: int, y: int, s: str): argument 2 has unexpected type 'float'

Thanks in advance!

**Comment by linbaiwpi** [comment]
> Traceback (most recent call last): File "C:\Users\usuario2\Downloads\8086-emulator-master\ui\codeeditor.py", line 150, in paintEvent self.codeEditor.lineNumberAreaPaintEvent(event) File "C:\Users\usuario2\Downloads\8086-emulator-master\ui\codeeditor.py", line 52, in lineNumberAreaPaintEvent painter.drawText(0, top, areaWidth - rightMargin, TypeError: arguments did not match any overloaded call: drawText(self, p: Union[QPointF, QPoint], s: str): argument 1 has unexpected type 'int' drawText(self, rectangle: QRectF, flags: int, text: str): argument 1 has unexpected type 'int' drawText(self, rectangle: QRect, flags: int, text: str): argument 1 has unexpected type 'int' drawText(self, rectangle: QRectF, text: str, option: QTextOption = QTextOption()): argument 1 has unexpected type 'int' drawText(self, p: QPoint, s: str): argument 1 has unexpected type 'int' drawText(self, x: int, y: int, width: int, height: int, flags: int, text: str): argument 2 has unexpected type 'float' drawText(self, x: int, y: int, s: str): argument 2 has unexpected type 'float'
> 
> Thanks in advance!

This is a known issue due to Python 3.10. You may downgrade your Python to 3.9. This issue will disappear.
