### ISSUE TITLE
请问需求的PyQt版本是多少？

### ISSUE THREAD

**Issue by linesoft2** [ZubinGou/8086-emulator#2]
猜测可能是版本不对，启动不了🥺
```
(base) PS C:\Users\l\Desktop\8086-emulator-master> python mainUI.py
Traceback (most recent call last):
  File "C:\Users\l\Desktop\8086-emulator-master\ui\codeeditor.py", line 150, in paintEvent
    self.codeEditor.lineNumberAreaPaintEvent(event)
  File "C:\Users\l\Desktop\8086-emulator-master\ui\codeeditor.py", line 52, in lineNumberAreaPaintEvent
    painter.drawText(0, top, areaWidth - rightMargin,
TypeError: arguments did not match any overloaded call:
  drawText(self, p: Union[QPointF, QPoint], s: str): argument 1 has unexpected type 'int'
  drawText(self, rectangle: QRectF, flags: int, text: str): argument 1 has unexpected type 'int'
  drawText(self, rectangle: QRect, flags: int, text: str): argument 1 has unexpected type 'int'
  drawText(self, rectangle: QRectF, text: str, option: QTextOption = QTextOption()): argument 1 has unexpected type 'int'
  drawText(self, p: QPoint, s: str): argument 1 has unexpected type 'int'
  drawText(self, x: int, y: int, width: int, height: int, flags: int, text: str): argument 2 has unexpected type 'float'
  drawText(self, x: int, y: int, s: str): argument 2 has unexpected type 'float'
```

**Comment by linesoft2** [comment]
已在`pyqt5==5.15.1`下成功启动
